/* 

// TODO : Completed Shop settings controller


TODO : Completed shops controller (Shops orders , shops Products, shops processed orders )

TODO : Completed shops management controller 


TODO : processed SupportTickets 

TODO : processed Orders

TODO : processed Refund Requests

TODO : processed Return Products Requests

TODO : Create shops orders based on User's Orders .

TODO : Create shops processed shop orders  .

TODO : Create notification system with sockit.io

TODO : Create scuduler tasks to send reports for shops owners and traders.

TODO : Planning for inventory management controller

TODO : Planning for enQuery (with shops traders ) controller =>>> jus an idea

TODO : Create full analytics for the  orders ,shops and products.

TODO : Create automated task for move the products form the products collection if it out of stock.


*/
