/* 

// TODO : Completed Shop settings controller

TODO : Completed shops controller (Shops orders ,shops processed orders )

TODO : Completed shops management controller 
TODO : Create shops orders based on User's Orders .

TODO : Shop support tickets 
TODO : shop processed supports tickets

TODO : processed SupportTickets 

!TODO : ensure user not return amount of product greater than the amount of product he bought. 

TODO : Create notification system with sockit.io
// TODO : processed Return Products Requests

//TODO : processed Refund Requests


TODO : using transactions for all the above controllers


TODO : Create scuduler tasks to send reports for shops owners and traders.



TODO : Create full analytics for the  orders ,shops and products.

TODO : Create automated task for move the products form the products collection if it out of stock.

TODO : Planning for inventory management controller

TODO : planning for shopping management process

*/
